### ISSUE TITLE
Clarification (Bangali Text). 

### ISSUE THREAD

**Issue by innat** [mjq11302010044/TPGSR#1]
I was reading your paper, interesting work. However, are you sure this is Bengali font? Can you check again? 

![font](https://user-images.githubusercontent.com/17668390/123950026-12ac5280-d9c5-11eb-96fe-26e76ea3d5ea.png)

**Comment by innat** [comment]
It should be referred to as **Sanskrit** language and it's studied that **Bengali** language is derived from **Sanskrit**, [quick discussion link](https://www.quora.com/Is-Bengali-a-language-derived-from-Sanskrit). There is debate (AFAIK) about their relationship, but I really don't care. 

I think this should be specified in the dataset you mentioned. The **Sanskrit** which is looks like [this](https://www.google.com/search?q=**Sanskrit**+language&newwindow=1&rlz=1C1CHBF_enBD940BD940&tbm=isch&sxsrf=ALeKk027JZcOaOLnsUWVIFYfZqWQiclwYQ:1625087721269&source=lnms&sa=X&ved=2ahUKEwi1oOvCo8DxAhUxzjgGHdv6DOEQ_AUoAnoECAEQBA&biw=1280&bih=631&dpr=1.5), and **Bengali** is looks like [this](https://www.google.com/search?q=**Bengali**+language&tbm=isch&ved=2ahUKEwju-83Go8DxAhXOTX0KHbp-C2YQ2-cCegQIABAA&oq=**Bengali**+language&gs_lcp=CgNpbWcQAzIECCMQJzIECAAQHjIECAAQHjIECAAQHjIECAAQHjIECAAQHjIECAAQHjIECAAQHjIECAAQHjIECAAQHjoGCAAQBxAeUL22AVi0vQFgnr8BaABwAHgAgAFpiAHABZIBAzIuNZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=8d7cYK6_Cs6b9QO6_a2wBg&bih=631&biw=1280&rlz=1C1CHBF_enBD940BD940).

**Comment by mjq11302010044** [comment]
@innat Thanks for telling us about this. Since we currently have little knowledge about the script font in the image, which is just an example, we may consider commenting on the dataset and make some clarifications in the future.
