### ISSUE TITLE
Request to add a license

### ISSUE THREAD

**Issue by jeswinoc** [mjq11302010044/TPGSR#15]
Hi Ma,
Great work on the paper and the implementation! I noticed that the repo did not have an license. I was wondering if you could add one so that I can understand the scope of use for the code.

Best,
Jeswin James

**Comment by mjq11302010044** [comment]
@jeswinoc Thanks a lot for the reminder! This repo follows the MIT license, it is okay to take the code for your own purpose (better NOT for criminals, lol). We will add this to our repo later.

**Comment by jeswinoc** [comment]
Thanks for the quick response @mjq11302010044 :)

**Comment by jeswinoc** [comment]
Sorry to Poke again, but would be adding the license anytime soon? I am planning to use the code for commercial use and it would be really helpful if you can add a license file :).

**Comment by mjq11302010044** [comment]
@jeswinoc Added, you can take it with your purpose :)
