### ISSUE TITLE
您好,可以发布预训练模型吗？

### ISSUE THREAD

**Issue by zhaoguoqing12** [mjq11302010044/TPGSR#2]
您好，我对您的研究非常感兴趣，方便发布预训练模型吗？
对我非常有用，感谢您的开源

**Comment by mjq11302010044** [comment]
@zhaoguoqing12 感谢关注，我们的模型不需要预训练。识别部分的预训练可以在repo中提供的链接进行下载。直接在TextZoom上训练即可。

**Comment by zhaoguoqing12** [comment]
> @zhaoguoqing12感谢关注，我们不需要模型训练预训练。识别部分的预训练可以在repo中提供的链接进行下载。直接在TextZoom上训练细菌。

非常感谢您的回复，我明白了

**Comment by zhaoguoqing12** [comment]
@mjq11302010044 
python3 main.py --arch="tsrn_tl_cascade" --test_model="CRNN" --batch_size=48 --STN --mask  --sr_share --gradient --go_test --stu_iter=1 --vis_dir='default' --resume="./crnn.pth" 
当使用您给的测试命令，出现如下错误
![Uploading image.png…]()

**Comment by mjq11302010044** [comment]
@zhaoguoqing12 不需要指定--resume参数，直接运行即可。

**Comment by zhaoguoqing12** [comment]
@mjq11302010044 非常抱歉再次打扰您，我有几个问题
1.您的项目和TextZoom的区别在哪里？或者说你是基于TextZoom代码上更改？
2.论文中所说的实验,都是为了公平比较您设计的SR和TP,从而只是重新训练crnn来评估吗？您设计的SR模块和TP模块不需要训练吗？或者是我理解有误
3.使用默认 sh test.sh 测试，会出现如下错误：
torch.Size([48, 3, 16, 64])
torch.Size([48, 3, 32, 128])
48
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    main(config, args, opt_TPG=opt)
  File "main.py", line 20, in main
    Mission.train()
  File "/data/guoqing/Image_deblurring/TPGSR-main/interfaces/super_resolution.py", line 483, in train
    aster_info
  File "/data/guoqing/Image_deblurring/TPGSR-main/interfaces/super_resolution.py", line 984, in eval
    metric_dict['psnr_lr'].append(self.cal_psnr(img_lr, img_hr))
  File "/data/guoqing/Image_deblurring/TPGSR-main/utils/ssim_psnr.py", line 15, in calculate_psnr
    mse = ((img1[:,:3,:,:]*255 - img2[:,:3,:,:]*255)**2).mean()
RuntimeError: The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 3
两种图片的大小不一致.

**Comment by mjq11302010044** [comment]
@zhaoguoqing12 你好，具体的细节请参考代码及论文原文。您反馈的错误我们已经修正，可以重新clone以获得最新版本的代码。

**Comment by zhaoguoqing12** [comment]
@mjq11302010044 已拷贝最新代码
python3 main.py --arch="tsrn_tl_cascade" --test_model="CRNN" --batch_size=48 --STN --mask  --sr_share --gradient --go_test --stu_iter=1 --vis_dir='default'
以上命令运行,似乎SR结果图片有问题
![image](https://user-images.githubusercontent.com/47818312/126272766-f1fc3eb6-7ff8-4aec-9ac4-7d4c4a4548b4.png)
![image](https://user-images.githubusercontent.com/47818312/126272828-8c3f9fc3-03fb-42f1-94b4-1fffa0da0712.png)

**Comment by zhaoguoqing12** [comment]
> @mjq11302010044已拷贝最新代码
> python3 main.py --arch="tsrn_tl_cascade" --test_model="CRNN" --batch_size=48 --STN --mask --sr_share --gradient --go_test --stu_iter=1 - -vis_dir='default'
> 以上命令运行，查看SR结果图片有问题
> ![图像](https://user-images.githubusercontent.com/47818312/126272766-f1fc3eb6-7ff8-4aec-9ac4-7d4c4a4548b4.png)
> ![图像](https://user-images.githubusercontent.com/47818312/126272828-8c3f9fc3-03fb-42f1-94b4-1fffa0da0712.png)

我明白了,我之前理解错你的意思了。你可以提供您训练好的模型吗？

**Comment by mjq11302010044** [comment]
@zhaoguoqing12 测试需要指定--resume参数，你把训练好的保存checkpoint的目录传进去即可

**Comment by zhaoguoqing12** [comment]
@mjq11302010044 我有问题想请教您
1.论文中调整TP 具体是如何调整增加的精度？
2.TP模型和最后预测的crnn模型可以说是一个模型吗？(感觉区别就是训练的数据不一样,两者是否可以互相使用)
3.因为模型在我数据集效果不好,我想构建自己的数据集训练,有较好的生成LR和HR图片对的方法吗？

**Comment by thebestYezhang** [comment]
> @mjq11302010044 我有问题想请教您
> 1.论文中调整TP 具体是如何调整增加的精度？
> 2.TP模型和最后预测的crnn模型可以说是一个模型吗？(感觉区别就是训练的数据不一样,两者是否可以互相使用)
> 3.因为模型在我数据集效果不好,我想构建自己的数据集训练,有较好的生成LR和HR图片对的方法吗？

您好，我最近也在看作者的代码和论文，关于代码运行有一些问题，可以给我一些指导吗？

**Comment by zhaoguoqing12** [comment]
> ，

相互指导吧，我并不是很熟悉。

**Comment by lvchungui** [comment]
> 

请问你是怎么在测试的时候获得图片的呀，我训练好了模型，但是不知道怎么获得SR图片

**Comment by llvhjgtdl** [comment]
> > ，
> 
> 相互指导吧，我并不是很熟悉。

请问您复现成功了吗。能达到作者说的精度吗
