### ISSUE TITLE
共享SR和非共享TP

### ISSUE THREAD

**Issue by zhaoguoqing12** [mjq11302010044/TPGSR#4]
论文中多阶段训练 提出使用共享SR和非共享TP,但是代码中写的是 非共享SR和共享TP
![image](https://user-images.githubusercontent.com/47818312/127737818-feb53bd2-529d-4dd2-837b-b602044d3fa6.png)
![image](https://user-images.githubusercontent.com/47818312/127737823-a31720d1-6889-4b15-9319-1a01eb553aa6.png)
根据你提出的训练命令
python3 -u main.py --arch="tsrn_tl_cascade" --batch_size=48 --STN --mask --use_distill --gradient --sr_share --stu_iter=3 --vis_dir='vis_TPGSR-TSRN'
--sr_share 默认为False,训练时是True

**Comment by vardenppp** [comment]
这里应该：上面是如果不sr_share，初始化多个sr模块，下面是初始化多个tpg模块。
但最后实际应用的时候，是根据是否share进行选择的，你可以搜一下“pick”，代码里写的是如果share，pick=0，否则pick=i。

**Comment by zhaoguoqing12** [comment]
@vardenppp 感谢,我看到了。所以训练不加 sr_share 并且 加上 tpg_share，才是共享SR和非共享TP。
